import { describe, expect, test } from "bun:test";
import { readFile } from "node:fs/promises";
import manifest from "../package.json";

describe("package manifest", () => {
  test("requires the OpenTUI runtime dependencies for Git package installs", () => {
    const metadata = (manifest as { peerDependenciesMeta?: Record<string, { optional?: boolean }> })
      .peerDependenciesMeta;

    expect(manifest.peerDependencies["@opentui/core"]).toBeDefined();
    expect(manifest.peerDependencies["@opentui/solid"]).toBeDefined();
    expect(manifest.peerDependencies["solid-js"]).toBeDefined();
    expect((manifest.dependencies as Record<string, string>)["solid-js"]).toBeUndefined();
    expect(metadata?.["@opentui/core"]?.optional).not.toBe(true);
    expect(metadata?.["@opentui/solid"]?.optional).not.toBe(true);
  });

  test("publishes Solid-compiled JavaScript instead of uncompiled TSX", async () => {
    expect(manifest.exports).toEqual({
      ".": "./dist/index.js",
      "./tui": "./dist/tui.js",
    });
    expect(manifest.files).toContain("dist");
    expect(manifest.files).not.toContain("src");

    const tui = await readFile(new URL("../dist/tui.js", import.meta.url), "utf8");
    expect(tui).toContain("Generated by `bun run build`");
    expect(tui).toContain('from "@opentui/solid"');
    expect(tui).not.toContain('from "@opentui/solid/jsx-runtime"');
  });
});
