import solidPlugin from "@opentui/solid/bun-plugin";

const result = await Bun.build({
  entrypoints: ["src/index.ts", "src/tui.ts"],
  target: "bun",
  format: "esm",
  outdir: "dist",
  packages: "external",
  plugins: [solidPlugin],
  banner: "// Generated by `bun run build`. Do not edit.",
});

for (const log of result.logs) {
  console.error(log);
}

if (!result.success) {
  process.exit(1);
}
